### ISSUE TITLE
repainted query w/ closed connection causes crash

### ISSUE THREAD

**Issue by asw-dev** [mispp/goat#17]
To reproduce

- open a connection
- query "select * from table;"
- open a new tab
- close/remove the connection
- switch to the tab that ran the query

**Comment by mispp** [comment]
Population of model behind tableview widget will have to be either way rewritten to load data in chunks because of issues in #2.

When this gets done, a signal could be emitted when connection gets closed for every model (in every tab) to clear contents.

**Comment by mispp** [comment]
should be solved with e8ced6c1fe868cf458b22afe521a4fc5b4889b33
