### ISSUE TITLE
package for arch

### ISSUE THREAD

**Issue by mispp** [mispp/goat#34]

**Comment by grawlinson** [comment]
Since this repository isn't versioned, I've created [`goat-git`](https://aur.archlinux.org/packages/goat-git/) on the AUR.

NB: The AUR package `goat` is taken by a pre-existing package.

**Comment by mispp** [comment]
Thank you!

As a note, versioning / tagging will come later:
1. when i learn how to do versioning / tagging
2. when we develop basic functionality like import/export

Going to leave this issue open until some confirmation that it works, then we can close it.

**Comment by mispp** [comment]
tried it on an arch install, works great.
closing the issue.
