### ISSUE TITLE
support mssql connections

### ISSUE THREAD

**Issue by mispp** [mispp/goat#62]
Via odbc?

**Comment by asw-dev** [comment]
As I understand it ms sql server developer edition can be used for testing so long as it is not used with commercial data and not deployed to production servers.

To install on ubuntu 18.04 via docker, follow these steps:

- install docker [guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04)
- get container `docker pull microsoft/mssql-server-linux`
- start server `docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<password>' -p 1433:1433 -d microsoft/mssql-server-linux:2017-CU8`
- run sqlcmd to create database `docker exec -it <container_id> /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P <password>`  (you can use `docker ps | grep '1433->1433' | cut -d ' ' -f 1` to find the containder_id)
- run any setup statements you want to test with. Use the GO keyword to execute the batch of statements, ctrl+d to quit.
```
CREATE DATABASE db;
GO
USE db;
CREATE TABLE foo (id int);
GO
SELECT * FROM foo;
GO
<ctrl+d>
```
- when finished you can stop the server with `docker stop <container_id>`

**Comment by asw-dev** [comment]
I'll add a guide on how to connect via Qt once I manage to get it working on my machine.

**Comment by asw-dev** [comment]
I managed to get Qt connection/queries working but haven't tried to repeat it on a fresh ubuntu image so there may be extra/missing steps.

- install odbc & freetds
    `sudo apt-get install unixodbc unixodbc-dev tdsodbc freetds-dev`

- code the database like so
```
    QSqlDatabase db = QSqlDatabase::addDatabase("QODBC", "id");

    db.setDatabaseName(QStringLiteral(
        "DRIVER=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so;"
        "Setup=/usr/lib/x86_64-linux-gnu/odbc/libtdsS.so;"
        "Server=127.0.0.1;"
        "Port=1433;"
        "UID=sa;"
        "PWD=password;"));
```
It looks like it is also possible to use have some of this stored in ini files, which may or may not be useful later.

It will be interesting to see what is needed to get this to run on windows.
